name: demo clase
on: [push]

jobs: 
  mensaje: 
    runs-on: ubuntu-latest

    steps: 
      - name: primer mensaje 
        run: echo "hola desde github actions"

      - name: segundo mensaje
        rrun: echo "este es el segundo paso automatico"

      - name: ver archivos del repositorio
        run: ls

